services:
    mc3k:
        image: postgres
        restart: always
        container_name: mc3k-v2
        ports:
            - 5433:5432
        environment:
            POSTGRES_DB: postgres_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
